### ISSUE TITLE
get alternative titles from "Also Known As"

### ISSUE THREAD

**Issue by AlyafeiAli** [chnthkksn/imdb-api#1]
Thank you for your hard work!
Is it possible to get a list of alternative movie/show titles from its "also known as" page?

**Comment by chnthkksn** [comment]
can u please be more specific about what you're asking for. ( with a image or something )
then ill add it for sure if it is possible.

**Comment by AlyafeiAli** [comment]
Sure. I meant the table found in pages like this one: https://www.imdb.com/title/tt0241527/releaseinfo/?ref_=tt_dt_aka#akas  
which has alternative titles of the movie or the show. Its URL generally looks like this: https://www.imdb.com/title/{IMDB-ID}/releaseinfo/?ref_=tt_dt_aka#akas

**Comment by chnthkksn** [comment]
ok now I get it. 
I don't think it is a common thing ( information ) to fetch with general details.
so I can add a separate endpoint for that if u want !

**Comment by AlyafeiAli** [comment]
> ok now I get it. I don't think it is a common thing ( information ) to fetch with general details. so I can add a separate endpoint for that if u want !

That would be great actually!  
Again, thank you for your hard work!

**Comment by chnthkksn** [comment]
Hello there, I added akas endpoint as you requested in dev branch, it works for now.
but needs more improvements. I'll improve it after my exams.
We can also use selenium for this task, but don't like to make it complicated. Hope u like it.

**Comment by AlyafeiAli** [comment]
Wow that was fast, thank you so much!
